### ISSUE TITLE
Using ~org-cliplink-retrieve-title-synchronously~ on a directory causes the directory to open in dired

### ISSUE THREAD

**Issue by GuiltyDolphin** [rexim/org-cliplink#105] opened 2018-07-13 15:50 UTC
For example, running `(org-cliplink-retrieve-title-synchronously "file:~/org")` (where`~/org` is a directory) causes a Dired buffer to open, as well as a `"Response buffer is nil!"` message to be printed to the minibuffer.

**Comment by rexim** [comment] 2018-07-13 16:08
@GuiltyDolphin thanks for reporting the problem! Could you please provide more details on what you expected from the function in this situation? Thanks!

**Comment by GuiltyDolphin** [comment] 2018-07-16 15:34
@rexim `org-cliplink-retrieve-title-synchronously` isn't an interactive command, so using it in Lisp to retrieve the title I wouldn't expect it to modify the user's current buffers/windows (or use `message`).

I would expect such a function to return either a string (when a title has been retrieved successfully), or `nil` (or a richer 'error' type) if the title could not be retrieved. It gets very confusing when dired buffers start popping up all over the place because a file path happened to be passed to the function.

**Comment by rexim** [comment] 2018-07-16 17:01
@GuiltyDolphin sounds reasonable. Thanks for such a detailed response! I'll try to find some time this week to fix the issue. If this problem is urgent feel free to submit a PR yourself. I will be happy to review and merge. Thanks!

**Comment by rexim** [comment] 2018-07-17 11:09
@GuiltyDolphin should be fixed by ef5e27c31e7acf593eb8e480bd52ea241099e12b. Please close the ticket if the problem is fixed. Thanks!

**Comment by rexim** [comment] 2018-07-24 10:11
@GuiltyDolphin it's been a week. So I'm gonna assume that the problem is fixed for you.

**Closed by rexim** 2018-07-24 10:11 UTC
Labels: bug

**Comment by GuiltyDolphin** [comment] 2018-08-06 10:03
@rexim This is fixed on my end, thank you! Apologies for not getting back to you sooner.
