### ISSUE TITLE
Error when trying to clip link

### ISSUE THREAD

**Issue by kirang89** [rexim/org-cliplink#78] opened 2016-02-16 18:05 UTC
**At times**, I get the following error when I try to clip a link:
```
Error while executing "gzip -c -q -d < /var/folders/hm/_yjrldxx5qd113j5jc4_qfm40000gn/T/org-cliplink47259bLU.gz"
```

I've tried reinstalling the package but with no success. 

Versions
------------
org-cliplink: 20151229.1100
Emacs: 24.5.1

Configuration
------------------
```
(add-hook 'org-mode-hook
	  (lambda ()
                  ......
                  (local-set-key (kbd "C-x p") 'org-cliplink)))
```

Any ideas as to what might be causing the problem?

**Comment by rexim** [comment] 2016-02-16 18:41
Hello Kiran! Thanks for the report! :)

What's your OS, btw?

> /var/folders/hm/_yjrldxx5qd113j5jc4_qfm40000gn/T/org-cliplink47259bLU.gz

This path looks strange. `org-cliplinkBlahBlah.gz` files are usually created in the temporary directory. Is `/var/folders/hm/_yjrldxx5qd113j5jc4_qfm40000gn/T/` really the tmp directory of your system? :) Could you please show me the value of your `temporary-file-directory` Emacs variable? Just do `C-h v temporary-file-directory RET` to see the value.

Also, the error message looks like a jka-compr error (jka-compr is just a standard Emacs module module responsible for compressing/uncompressing stuff). Do you have any buffers with name like `*jka-compr-error*` around after reproducing the problem? If you do, please post its content here.

Thanks!

**Comment by kirang89** [comment] 2016-02-16 23:09
Thanks for the prompt reply! :)

> What's your OS, btw?

OSX ElCapitan

> Could you please show me the value of your temporary-file-directory Emacs variable?

```
temporary-file-directory is a variable defined in `C source code'.
Its value is "/var/folders/hm/_yjrldxx5qd113j5jc4_qfm40000gn/T/"

```

> Do you have any buffers with name like *jka-compr-error* around after reproducing the problem? If you do, please post its content here.

```
Error while executing "gzip -c -q -d < /var/folders/hm/_yjrldxx5qd113j5jc4_qfm40000gn/T/org-cliplink19086dhL.gz"
```

**Comment by rexim** [comment] 2016-02-17 04:36
Alright, thanks for the information. I have no idea what could happen there. I've never actually test org-cliplink on OSX. And to be honest, never actually used OSX itself (I'm more of a Linux guy). :) But I have a full office of colleagues with macbooks. :D So I'll try reproduce your problem on my side.

And the last question just to clarify. Where did you get your Emacs build? Is it from http://emacsformacosx.com/, right?

**Comment by kirang89** [comment] 2016-02-17 14:45
> Where did you get your Emacs build? Is it from http://emacsformacosx.com/, right?

Yes, that's right.

If it helps, I didn't have this problem when I first started using org-cliplink. I'm not sure if an update broke it or if it's some issue with my Emacs setup.

**Comment by rexim** [comment] 2016-02-18 07:24
I've just checked a freshly installed Emacs 24.5.1 on OSX ElCapitan with org-cliplink 20151229.1100 and I am able to cliplink http://github.com/ (it returns gzip content, so it triggers gzip related parts of org-cliplink). Everything works perfectly for me.

Maybe something in your configuration created a situation in which org-cliplink doesn't work, I don't know... This is your currently Emacs configuration, right? https://github.com/kirang89/.emacs.d If so I'll try to analyse it in a couple of days and see if anything can break org-cliplink.

Thanks!

**Comment by kirang89** [comment] 2016-02-18 16:16
>  I am able to cliplink http://github.com/ (it returns gzip content, so it triggers gzip related parts of org-cliplink). Everything works perfectly for me.

I can clip links as well. This problem does not occur all the time. Sometimes I am unable to clip 3-5 links in a row and sometimes I can do so without any problems.

>  This is your current Emacs configuration, right? https://github.com/kirang89/.emacs.d If so I'll try to analyse it in a couple of days and see if anything can break org-cliplink.

Yes it is. Thank you for offering to take time out to look into my setup. Appreciate it!

**Comment by rexim** [comment] 2016-02-20 19:53
I'm in the middle of enabling CI for OSX and I can already see that the gziped https integration tests are failing for some reason %)

https://travis-ci.org/rexim/org-cliplink/jobs/110066594#L385

**Comment by rexim** [comment] 2016-02-20 20:28
Even though, there is something wrong with our gzipped testing server #62, I think this could be your case. Maybe some of the servers you are trying to cliplink from are just closing their connections with some bytes remaining too. Anyway continue to investigate that further.

**Comment by kirang89** [comment] 2016-02-21 07:25
What I get when I run `./run-travis-ci.sh`:

```
Ran 8 tests, 4 results as expected, 4 unexpected (2016-02-21 12:52:44+0530)

4 unexpected results:
   FAILED  org-cliplink-escape-title--gziped-https
   FAILED  org-cliplink-escape-title--http
   FAILED  org-cliplink-simple-title--gziped-http
   FAILED  org-cliplink-simple-title--http
```

**Comment by rexim** [comment] 2016-05-26 05:23
@kirang89, Hello! It's been a while since we talked about this issue. Sorry for not updating it for such a long time. org-cliplink is a personal project, so it's not always possible to find enough resources to work on it. :) Unfortunately, I had tried everything I could to reproduce your problem. May I ask you? Do you still experience this issue?

**Comment by kirang89** [comment] 2016-05-26 08:52
@rexim I appreciate you for taking your time to look into this :)

I had removed the package a few days after our previous conversation since I was unable to figure out a solution. Last week, I decided to give it another go and installed the package and haven't had a problem since. 

I'll reopen this issue if I find any problems, but do feel free to close this for now.

**Closed** 2016-05-26 08:53 UTC
Labels: incident, OS: OSX

**Comment by rexim** [comment] 2016-05-26 08:59
@kirang89 cool! Thank you very much! :)
